#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

banner "Talent Hive AWS CI/CD credentials"

# ── Stage 1: preflight -----------------------------------------------------
stage "Preflight"
say "We'll wire AWS credentials and app secrets into this repo's GitHub"
say "Actions so the Deploy workflow (build images, terraform apply to ECS) can run."
if ! command -v gh >/dev/null 2>&1; then
  warn "gh CLI not found - secrets/variables won't be set. Install it first."
elif ! gh auth status >/dev/null 2>&1; then
  warn "gh is not authenticated - secrets/variables won't be set. Run 'gh auth login' first."
else
  note "gh is ready. ✓"
fi
if ! command -v aws >/dev/null 2>&1; then
  warn "aws CLI not found. Stage 3 (state bucket) will need you to create it in the console."
else
  note "aws CLI is ready. ✓"
fi
pause "Press Enter to continue"

# ── Stage 2: IAM user + AWS GitHub secrets ----------------------------------
stage "IAM user for GitHub Actions"
say "Create an IAM user that the pipeline will use to push images to ECR and"
say "run 'terraform apply' against your AWS account."
open_url "https://console.aws.amazon.com/iam/home#/users"
step "Click 'Create user'. Set username 'talent-hive-github-ci', select"
step "  'Provide user access to the AWS Management Console' = NO (programmatic only)."
step "On the permissions page, attach the 'AdministratorAccess' managed policy"
step "  (this provisions EC2/RDS/Redis/ECS/S3/ECR/Secrets Manager; scope it down later if you like)."
step "Create the user, then open it and click 'Create access key' (CLI option)."
step "Copy the Access key ID and the Secret access key (shown once)."
ask_secret AWS_ACCESS_KEY_ID "Paste the Access key ID:"
ask_secret AWS_SECRET_ACCESS_KEY "Paste the Secret access key:"
write_env AWS_ACCESS_KEY_ID "$AWS_ACCESS_KEY_ID"
write_env AWS_SECRET_ACCESS_KEY "$AWS_SECRET_ACCESS_KEY"
set_secret AWS_ACCESS_KEY_ID "$AWS_ACCESS_KEY_ID"
set_secret AWS_SECRET_ACCESS_KEY "$AWS_SECRET_ACCESS_KEY"

# ── Stage 3: S3 state bucket + DynamoDB lock table --------------------------
stage "Terraform remote state (S3 + DynamoDB)"
say "The pipeline needs an S3 bucket for tfstate and a DynamoDB table for lock."
say "We'll create both with the aws CLI now (they're idempotent)."
if command -v aws >/dev/null 2>&1 && [[ -n "$AWS_ACCESS_KEY_ID" ]]; then
  export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
  ask AWS_REGION "AWS region (default eu-west-2)"
  export AWS_DEFAULT_REGION="$AWS_REGION"
  _bucket="talent-hive-tfstate-${AWS_ACCESS_KEY_ID:0:8}"
  step "Creating S3 bucket \`${_bucket}\`..."
  aws s3api create-bucket --bucket "$_bucket" --region "$AWS_REGION" --create-bucket-configuration LocationConstraint="$AWS_REGION" >/dev/null 2>&1 || true
  aws s3api put-bucket-versioning --bucket "$_bucket" --versioning-configuration Status=Enabled >/dev/null 2>&1 || true
  _lock="talent-hive-tf-lock"
  step "Creating DynamoDB table \`${_lock}\`..."
  aws dynamodb create-table --table-name "$_lock" --attribute-definitions AttributeName=LockID,AttributeType=S --key-schema AttributeName=LockID,KeyType=HASH --billing-mode PAY_PER_REQUEST >/dev/null 2>&1 || true
  export TF_BACKEND_BUCKET="$_bucket"
  export TF_BACKEND_LOCK_TABLE="$_lock"
  set_var TF_BACKEND_BUCKET "$_bucket"
  set_var TF_BACKEND_LOCK_TABLE "$_lock"
  note "State bucket: $_bucket"
  note "Lock table:   $_lock"
else
  say "We couldn't run aws CLI, so create these by hand:"
  open_url "https://s3.console.aws.amazon.com/s3/bucket/create"
  ask TF_BACKEND_BUCKET "S3 bucket name for tfstate (must be globally unique):"
  open_url "https://console.aws.amazon.com/dynamodbv2/home#/create-table"
  ask TF_BACKEND_LOCK_TABLE "Lock table name (or use the default):"
  set_var TF_BACKEND_BUCKET "$TF_BACKEND_BUCKET"
  set_var TF_BACKEND_LOCK_TABLE "$TF_BACKEND_LOCK_TABLE"
fi

# ── Stage 4: region + backend key variables ---------------------------------
stage "Backend region and state key"
say "Record the Terraform backend region and state key path as GitHub variables."
ask AWS_REGION "AWS region (default eu-west-2)"
if [[ -z "${TF_BACKEND_KEY:-}" ]]; then
  TF_BACKEND_KEY="talent-hive/terraform.tfstate"
fi
ask TF_BACKEND_KEY "State key path (default talent-hive/terraform.tfstate)"
write_env AWS_REGION "$AWS_REGION"
set_var AWS_REGION "$AWS_REGION"
set_var TF_BACKEND_KEY "$TF_BACKEND_KEY"

# ── Stage 5: Telegram bot token ---------------------------------------------
stage "Telegram bot token"
say "Create (or reuse) your bot with @BotFather and copy its token."
open_url "https://t.me/BotFather"
step "Send /newbot, pick a name and username. BotFather replies with an HTTP API token."
step "Copy the token (looks like 123456:ABC-DEF...)."
ask_secret TELEGRAM_TOKEN "Paste the Telegram bot token:"
write_env TH_TELEGRAM_TOKEN "$TELEGRAM_TOKEN"
set_secret TELEGRAM_TOKEN "$TELEGRAM_TOKEN"

# ── Stage 6: Groq API key (optional) -----------------------------------------
stage "Groq API key (optional)"
say "Used for AI generation. Leave the value empty to skip this provider."
open_url "https://console.groq.com/keys"
step "Create an API key and copy it."
ask_secret GROQ_API_KEY "Paste the Groq API key (or press Enter to skip):"
if [[ -n "$GROQ_API_KEY" ]]; then
  write_env TH_GROQ_API_KEY "$GROQ_API_KEY"
  set_secret GROQ_API_KEY "$GROQ_API_KEY"
fi

# ── Stage 7: Google AI API key (optional) ------------------------------------
stage "Google AI API key (optional)"
say "Used for AI generation. Leave the value empty to skip this provider."
open_url "https://aistudio.google.com/app/apikey"
step "Create an API key and copy it."
ask_secret GOOGLE_AI_API_KEY "Paste the Google AI API key (or press Enter to skip):"
if [[ -n "$GOOGLE_AI_API_KEY" ]]; then
  write_env TH_GOOGLE_AI_API_KEY "$GOOGLE_AI_API_KEY"
  set_secret GOOGLE_AI_API_KEY "$GOOGLE_AI_API_KEY"
fi

# ── Stage 8: validate deploy --------------------------------------------------
stage "Onboarding the local terraform state"
say "Last: point local terraform at the shared state and confirm it can plan."
warn "This stage is read-only (plan); it doesn't apply anything."
if command -v terraform >/dev/null 2>&1; then
  pushd infra >/dev/null 2>&1 || true
  note ">>> terraform init (backend)..."
  terraform init -backend-config="bucket=$TF_BACKEND_BUCKET" -backend-config="key=$TF_BACKEND_KEY" -backend-config="region=$AWS_REGION" -backend-config="dynamodb_table=$TF_BACKEND_LOCK_TABLE" -no-color 2>&1 | tail -n 5
  note ">>> terraform plan..."
  terraform plan -input=false -no-color 2>&1 | tail -n 15
  popd >/dev/null 2>&1 || true
else
  say "terraform CLI not installed locally - skip this. The Deploy workflow will"
  say "provision on your next merge to main, or from 'Actions -> Deploy -> Run workflow'."
fi
say ""
say "To validate end-to-end, merge your CI/CD changes to main (or trigger the"
say "Deploy workflow manually) and watch it build images, run terraform apply, and deploy to ECS."

finish
